### ISSUE TITLE
Unexpected error fetching ESO data

### ISSUE THREAD

**Issue by Zhalias** [webmake/eso-ha#1]
Sveiki, gal patartumėte kuria kryptimi žiūrėti:

Logger: custom_components.eso.sensor
Source: custom_components/eso/sensor.py:104
Integration: eso ([documentation](https://*****************/config/logs))
First occurred: 09:56:52 (3 occurrences)
Last logged: 11:56:52

Unexpected error fetching ESO data: RestData.__init__() missing 1 required positional argument: 'ssl_cipher_list'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 217, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/eso/sensor.py", line 74, in async_update_data
    cookie = await authAndGetToken(hass, username, password)
  File "/config/custom_components/eso/sensor.py", line 104, in authAndGetToken
    restInit = RestData(hass, METHOD_GET, _ENDPOINT_AUTH, DEFAULT_ENCODING, None, None, None, None, DEFAULT_VERIFY_SSL)
TypeError: RestData.__init__() missing 1 required positional argument: 'ssl_cipher_list'

**Comment by webmake** [comment]
Dėkoju už pastebėjimą, pataisyta
